### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by JuanitoFatas** [ryanflorence/react-training#25]
Hi I cloned this repo, npm install:

```
$ npm install
npm WARN package.json react-training@0.0.1 No repository field.
```

then `npm start` failed:

```
> react-training@0.0.1 start /Users/Juan/react/react-training
> http-server

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at doNTCallback3 (node.js:440:9)
    at process._tickCallback (node.js:346:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! react-training@0.0.1 start: `http-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-training@0.0.1 start script 'http-server'.
npm ERR! This is most likely a problem with the react-training package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-training
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Juan/react/react-training/npm-debug.log
```

contents of `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-training@0.0.1
6 info start react-training@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info react-training@0.0.1 Failed to exec start script
9 verbose stack Error: react-training@0.0.1 start: `http-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-training@0.0.1
11 verbose cwd /Users/Juan/react/react-training
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error react-training@0.0.1 start: `http-server`
17 error Exit status 1
18 error Failed at the react-training@0.0.1 start script 'http-server'.
18 error This is most likely a problem with the react-training package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     http-server
18 error You can get their info via:
18 error     npm owner ls react-training
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Thanks!

**Comment by vu3mmg** [comment]
npm start gives the following "npm ERR! missing script: start"
